version: "3.1"
services:
  server-config:
    build: './server-configuration/'
    ports:
       - "8888:8888"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "memes"
  service-images:
    build: './service-images/'
    ports:
      - "8080:8080"
    environment:    
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"