version: "3.1"
services:
  server-config:
    build: './server-configuration/'
    ports:
       - "8888:8888"
  server-eureka:
    build: './server-eureka/'
    ports:
       - "8761:8761"
  server-zuul:
    build: './server-zuul/'
    ports:
       - "5555:5555"
    environment:
       EUREKASERVER_PORT:   "8761"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "memes"
  service-images:
    build: './service-images/'
    ports:
      - "8080:8080"
    environment:    
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
  service-images-metadata:
    build: './service-images-metadata/'
    ports:
      - "8081:8081"
    environment:    
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
  service-tags:
    build: './service-tags/'
    ports:
      - "8082:8082"
    environment:    
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"