spring:
  application:
    name: server-zuul

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://server-eureka:8761/eureka/
      
management: 
  endpoints: 
    web: 
      exposure: 
        include: 'routes'

server:
  port: 5555
  
zuul:
  sensitive-headers:
  ignored-services: 'service-images-metadata'
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    service-images: /images/**
    service-tags: /tags/**
    spring-security-oauth-resource:
      path: /auth/**
      url: http://server-security:8901/